apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.name }}
  labels:
    app: {{ printf "%s-%s" .Release.Name .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Release.Name .Values.name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.docker.secretName }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        args:
        - --interval={{ .Values.interval }}
        - --labels={{ .Values.labels }}
        - --annotations={{ .Values.annotations }}
        - --namespaces={{ .Values.namespaces }}
        - --location={{ .Values.location }}
        - --off-days={{ .Values.offDays }}
        - --holidays={{ .Values.holidays }}
        - --chaos-hours=start:{{ .Values.chaosHrs.start }},end:{{ .Values.chaosHrs.end }}
        {{- if not .Values.dryRun }}
        - --no-dry-run
        {{- end }}
        {{- if .Values.limitChaos }}
        - --limit-chaos
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.resources.cpu }}
            memory: {{ .Values.resources.memory }}
          limits:
            cpu: {{ .Values.resources.cpu }}
            memory: {{ .Values.resources.memory }}
