apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chaoskube
  labels:
    app: chaoskube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      serviceAccountName: chaoskube
      containers:
      - name: chaoskube
        image: quay.io/linki/chaoskube:v0.6.2
        args:
        # kill a pod every 10 minutes
        - --interval=10m
        # only target pods in the test environment
        - --labels=environment=test
        # only consider pods with this annotation
        - --annotations=chaos.alpha.kubernetes.io/enabled=true
        # exclude all pods in the kube-system namespace
        - --namespaces=!kube-system
        # terminate pods for real: this disables dry-run mode which is on by default
        - --no-dry-run
        # limit chaos times as specified in following options (default is off)
        # --no-limit-chaos or missing options turns this off
        - --limit-chaos
        # timezone location from the "tz database" (e.g. "America/Los_Angeles") NO DEFAULT
        # also allowed: "UTC" or "Local"
        - --location=Local
        # comma-separated list of weekday names when chaos is suspended. Default: "Saturday,Sunday".
        # (Use "none" for no off days.)
        - --off-days=
        # list of ISO 8601 dates (YYYY-MM-DD) when chaos is suspended. Default: empty list.
        - --holidays=
        # daily start and end times for introducing chaos. Default: start:9:30,end:16:30
        - --chaos-hours=

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaoskube
